### ISSUE TITLE
Array to control group of leds

### ISSUE THREAD

**Issue by BjornB2** [jandelgado/jled-pca9685-hal#2]
Hi! 

First of all, thanks for the library. It seems a great fit for what I am trying to do, which is randomly light up leds out of a total of a few hundred leds.
I'm trying to control the leds with an array (called led[] in my below code), but I have trouble finding out what type it should be. For JLed it seems there is a JLed type but how about the PCA version?

If I use the below code without an array (so every led it's own code/lines) it does what I want, but that is not really feasible for hundreds of leds I think :)

```
#include <jled-pca9685-hal.h>

constexpr auto I2C_ADDRESS = 0x40;
auto i2c = TwoWire();
auto pwm = Adafruit_PWMServoDriver(I2C_ADDRESS, i2c);

jled::JLedPCA9685 JLedPCA9685(jled::PCA9685Hal::PinType pin) {
    return jled::JLedPCA9685(jled::PCA9685Hal(pin, &pwm));
}
const int nLeds = 4; //Number of leds
TYPE? led[nLeds]; // <-- HERE

int fadeIn = 2000; //Fade in tijd in ms

int fadeOut = 2000; //Fade out tijd in ms



int randomDelay;
int randomOn;

//Init sequence. Test all leds at the same time
void loop() {
   for (int i=0; i<nLeds; i++) {
      led[i] = JLedPCA9685(i).Breathe(1000,1000,1000);
   }
}

void setup() {
    Serial.begin(9600);
    Serial.println("Program start");
    pwm.begin();

}

void loop() {
   for (int i=0; i<nLeds; i++) {
      led[i].Update();
      if (led[i].IsRunning() == false) {
          Serial.println("New cycle");
          led[i].Reset();
          randomDelay=random(0,20000);
          randomOn=random(0,20000);
          Serial.println(randomDelay);
          Serial.println(randomOn);
          led[i] = JLedPCA9685(i).Breathe(fadeIn,randomOn,fadeOut).DelayBefore(randomDelay);
    
      }
    
   }

}
```

Also, I want to chain multiple PCA's to control a lot of LED's and preferably use all leds across all boards in the same array. Is this possible?

Thanks!

Björn

**Comment by jandelgado** [comment]
@BjornB2: Without changing code in the `JLed` lib (would require a default constructor, which I'm not sure we should have here - but this is another story), I think this would solve your problem:

```c++
constexpr auto nLeds = 4; //Number of leds
auto buf = operator new[](nLeds * sizeof(jled::JLedPCA9685));
auto led = static_cast<jled::JLedPCA9685*>(buf);

// led is now an (uninitialized) array of JLed objects
```

Could not try out the code, please let me know if it works for you

**Comment by BjornB2** [comment]
Works like a charm! Thanks!

**Comment by jandelgado** [comment]
Hi @BjornB2 , some minor suggestions for your code:

```c++
  led[i].Update();
  if (led[i].IsRunning() == false) {
```

simplifies to 

```c++
      if (led[i].Update() == false) {
```

And 
```c++
 led[i] = JLedPCA9685(i).Breathe(fadeIn,randomOn,fadeOut).DelayBefore(randomDelay);
```

can be written as

```c++
 led[i].Breathe(fadeIn,randomOn,fadeOut).DelayBefore(randomDelay);
```
The `Reset()` is also not needed, since changing the effect will call `Reset` implicitely.

**Comment by BjornB2** [comment]
Hi @jandelgado, 

Thanks for the input! I'll try this tomorrow. Also trying to get multiple PCA9685 boards in an array and adding some code to automagically pick the right board based on pin number. I think I got it now but the hardware is at home and I am not 😊
If all works now I have around 50 lines of code left from the almost 300 for the first working version.
I'll keep you updated!

Regards
Björn

**Comment by BjornB2** [comment]
Hi!

One more strange thing with arrays. 

If I fill the array that I use for the board addresses 'manually' it works fine:
```
Adafruit_PWMServoDriver drivers[] = {
  Adafruit_PWMServoDriver(0x40),
  Adafruit_PWMServoDriver(0x41),
  Adafruit_PWMServoDriver(0x42),
  Adafruit_PWMServoDriver(0x43),
  Adafruit_PWMServoDriver(0x44),
  Adafruit_PWMServoDriver(0x45),
  Adafruit_PWMServoDriver(0x46),
  Adafruit_PWMServoDriver(0x47),
  Adafruit_PWMServoDriver(0x48),
  Adafruit_PWMServoDriver(0x49),
  Adafruit_PWMServoDriver(0x4A),
  Adafruit_PWMServoDriver(0x4B),
  Adafruit_PWMServoDriver(0x4C),
  Adafruit_PWMServoDriver(0x4D),
  Adafruit_PWMServoDriver(0x4E),
  Adafruit_PWMServoDriver(0x4F),
  Adafruit_PWMServoDriver(0x50),
  Adafruit_PWMServoDriver(0x51),
  Adafruit_PWMServoDriver(0x52),
  Adafruit_PWMServoDriver(0x53),
  Adafruit_PWMServoDriver(0x54),
  Adafruit_PWMServoDriver(0x55),
  Adafruit_PWMServoDriver(0x56),
  Adafruit_PWMServoDriver(0x57),
  Adafruit_PWMServoDriver(0x58),
  Adafruit_PWMServoDriver(0x59),
  Adafruit_PWMServoDriver(0x5A),
  Adafruit_PWMServoDriver(0x5B),
  Adafruit_PWMServoDriver(0x5C),
  Adafruit_PWMServoDriver(0x5D),
  Adafruit_PWMServoDriver(0x5E),
  Adafruit_PWMServoDriver(0x5F),
  Adafruit_PWMServoDriver(0x60),
  Adafruit_PWMServoDriver(0x61),
  Adafruit_PWMServoDriver(0x62),
  Adafruit_PWMServoDriver(0x63),
  Adafruit_PWMServoDriver(0x64),
  Adafruit_PWMServoDriver(0x65),
  Adafruit_PWMServoDriver(0x66),
  Adafruit_PWMServoDriver(0x67),
  Adafruit_PWMServoDriver(0x68),
  Adafruit_PWMServoDriver(0x69),
  Adafruit_PWMServoDriver(0x6A),
  Adafruit_PWMServoDriver(0x6B),
  Adafruit_PWMServoDriver(0x6C),
  Adafruit_PWMServoDriver(0x6D),
  Adafruit_PWMServoDriver(0x6E),
  Adafruit_PWMServoDriver(0x6F),
  Adafruit_PWMServoDriver(0x70),
  Adafruit_PWMServoDriver(0x71),
  Adafruit_PWMServoDriver(0x72),
  Adafruit_PWMServoDriver(0x73),
  Adafruit_PWMServoDriver(0x74),
  Adafruit_PWMServoDriver(0x75),
  Adafruit_PWMServoDriver(0x76),
  Adafruit_PWMServoDriver(0x77),
  Adafruit_PWMServoDriver(0x78),
  Adafruit_PWMServoDriver(0x79),
  Adafruit_PWMServoDriver(0x7A),
  Adafruit_PWMServoDriver(0x7B),
  Adafruit_PWMServoDriver(0x7C),
  Adafruit_PWMServoDriver(0x7D)
};
```

But when I replace this with

```
Adafruit_PWMServoDriver drivers[numberOfBoards] = {
  Adafruit_PWMServoDriver(0x40)
};

.....

void setup() {

  for (int i = 0; i < numberOfBoards; i++) {
    drivers[i] = Adafruit_PWMServoDriver(0x40 + i);
  }
}
```
The breathing-in and out effect start flickering. In between the leds are on normally.

**Comment by jandelgado** [comment]
I don't know the `Adafruit_PWMServoDriver` library too well, but some thoughts:

* you are initializing address 0x40 twice in your example
* I'm not sure if a single I2C bus is capable of driving that much devices (every change in a LEDs state will write out a few bytes on the I2C bus) - perhaps it's too much. Test what happens when you reduce the `numberOfBoards` - does the problem persist?
* If that is the problem: try using multiple I2C busses (e.g. the ESP32 has 2)
* try using an array of pointers
```c++
Adafruit_PWMServoDriver *drivers[numberOfBoards] = {};
.....
void setup() {
  for (int i = 0; i < numberOfBoards; i++) {
    drivers[i] = new Adafruit_PWMServoDriver(0x40 + i);
  }
}
```
* Try to optimize the `Adafruit_PWMServoDriver` for your use case, for example by taking control over the `beginTransmission()` / `endTransmission()` blocks: write larger chunks of data in a transmission by controlling the transmissions in your application explicitely and removing the calls from the Adafruit lib. See 

https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library/blob/2b789da2f0a1545c0fa481091b8ef8d4e694fc4c/Adafruit_PWMServoDriver.cpp#L234-L240)
* Experiment with [setclock](https://www.arduino.cc/reference/en/language/functions/communication/wire/setclock/)

How many JLed objects are you driving, and what micro controller are you using?

Good luck!

**Comment by BjornB2** [comment]
Thanks again for your reply. The input is much appreciated.

If I fill the drivers[] array manually it runs fine. I can add the maximum of 62 boards this way without having problems. I can't actually use 62*16 = 992 LEDs total because the for loop later in the code starts being an issue, but using 160 LEDS after initializing 62 boards works fine. 

I must mention that physically I have only 2 boards connected. 

But what is so strange that if I fill the drivers[] array by using a for loop, which I think should result in exactly the same array, I get the blinking.

I am first creating the array with a set size and filling it with the 0x40 value and then later overwriting the values by the actual values. It doesn't matter how many boards I init this way, it is always blinking. Even with 2 boards.

As you probably can tell by now I am not a seasoned programmer, so there probably are some errors in my thinking somewhere. Also the last couple of possible solutions you mention are a bit above my capabilities I am afraid.

In the end I got it all working by filling the array manually but it simply doesn't look very good :)

I am using a ESP8266 board by the way.

Anyway, it's not that important and I guess you have better things to do, so I'll just keep it as is. 

Thank you very much for your patience and help!

Björn

**Comment by jandelgado** [comment]
I think the problem is somewhere in the code you omitted. Where do you call `begin()` on the  `Adafruit_PWMServoDriver` object?
Could you please post the whole sketch?

**Comment by BjornB2** [comment]
The begin() is called in setup. Filling the array is done before the setup. 
I've completed the project without filling the array with a for loop. As long as I fill it manually it all works fine so I kept it that way. 

Thanks again for your help!
